version: '3.8'

services:

  paycheck_cloud:
    container_name: paycheck_cloud-n
    build:
      context: ./paycheck-cloud/paycheck
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/paycheck-cloud/paycheck-cloud/_persistent_store:/paycheck/scratch/_save
    environment:
      - FLASK_ENV=production
      - FLASK_APP=backup_server.py
    ports:
      - "50030:50030"


# COMMAND BASICS

# docker-compose build        # Build the images
#                             # look for a docker-compose.yml file in the current directory,
#                             # & build images for all the services defined based on their build configs.

# docker-compose up -d        # run containers  -d runs in detached/background mode.

# docker-compose down         # Stop the containers

# docker-compose logs -f      # View logs from all containers
# docker-compose exec app sh  # Shell into a container
# docker-compose restart      # Restart all containers
